
name: CI
on:
  push:
    branches: ["**"]
  pull_request:
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest
        run: pytest -q
  docker-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t aceest-fitness-app:ci .
      - name: Run pytest inside Docker
        run: docker run --rm aceest-fitness-app:ci pytest -q
